server:
  port: 8089
  servlet:
    context-path: /my-app

spring:
  redis:
    database: 0
    host: localhost
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 8
        min-idle: 0
        max-idle: 8
        max-wait: 1
      shutdown-timeout: 5000
  session:
    store-type: redis
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.100.249.62:3306/test?user=root&password=123456&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

mybatis:
    mapper-locations: classpath:mapping/*.xml
    type-aliases-package: com.lfs.entity
logging:
  level:
    com.lfs: debug
  file:
    name: /Users/simplelv/test.log
